### ISSUE TITLE
Questions about TEMP_SSD0 (0x0D)

### ISSUE THREAD

**Issue by MouchenHung-QUANTA** [facebook/OpenBIC#104]
Hi @rainlinWW,

We have a question about sensor reading on TEMP_SSD0 (0x0D). Why there's no ".cache" value given while sensor reading back with 0x80. I know that this scenario might be happened sometime. But in this case, BIC sensor polling might read back last(including correct value or even 0xFF if read failed last time) or unknown value which cause wrong reading issue.

Thanks,
Mouchen

**Comment by YoungLi123** [comment]
Fixed by #107
