### ISSUE TITLE
Include different header of cmsis

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#106]
Hi @rainlinWW,

The code includes two kinds of cmsis header(cmsis_os.h and cmsis_os2.h).
The value of "osPriorityBelowNormal" is different in these headers,  should they all use same header?

Thanks,
Yi-Shum

**Comment by rainlinWW** [comment]
Hi @Yi-Shum 

Yes, they should use same header.

Thanks,
Rain

**Comment by Yi-Shum** [comment]
fby3.5: cl: Added IPMB freq set and IPMB enable (#119) solve this issue.
