### ISSUE TITLE
Questions about GPIO platform code

### ISSUE THREAD

**Issue by MouchenHung-QUANTA** [facebook/OpenBIC#114]
Hi @rainlinWW 

In "name_gpioQ" macro from plat_gpio.h. There's no "Reserve_GPIOQ2" pin. Is that right?

Thanks,
Mouchen

**Comment by rainlinWW** [comment]
Hi @MouchenHung-QUANTA 

We checked GPIOQ2 missing, will fix it soon.

Thanks,
Rain

**Comment by MouchenHung-QUANTA** [comment]
Hi @rainlinWW

Got it!

Thanks,
Mouchen

**Comment by rainlinWW** [comment]
Hi @MouchenHung-QUANTA 

Reserve_GPIOQ2 added with #119, thanks for reminder

Thanks,
Rain
