### ISSUE TITLE
Add OEM platform command

### ISSUE THREAD

**Issue by MouchenHung-QUANTA** [facebook/OpenBIC#161]
Hi @rainlinWW,

In order to debug or get some server's info while BIC running, we have a suggestion to add an OEM platform command in BIC console which may includes GPIO get/set or other topics in further.
Is that ok for you?

p.s. Bellow is one of the example from current work.
 
![GPIO_EX1](https://user-images.githubusercontent.com/68039143/153351969-a3f9b433-72bf-431d-980f-0b8207dc5650.png)

Thanks,
Mouchen

**Comment by rainlinWW** [comment]
Hi @MouchenHung-QUANTA 

We think it a great command and very useful during development.
But there is a concern that Zephyr doesn't support reading GPIO direction and it might be risky to return recorded status in GPIO table.

Thanks,
Rain

**Comment by MouchenHung-QUANTA** [comment]
Hi @rainlinWW,

Indeed, zephyr-aspeed gpio driver doesn't support direction get/set api, so I used GPIO table's (gpio_cfg) direction instead temporary to get initial sets. Even though, this could be discussed or modified in the future.

Thanks,
Mouchen

**Comment by MouchenHung-QUANTA** [comment]
Hi @rainlinWW,

According to your doubt, we thought that getting direction from the table may not cause serious problem. If there's any way to get current gpio direction in the future, we will update table synchronously.

Thanks,
Mouchen

**Comment by rainlinWW** [comment]
Hi @MouchenHung-QUANTA 

Ok, thanks for your help.

Thanks,
Rain
