### ISSUE TITLE
Schedule for when I3C will be implement

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#175]
Hi @rainlinWW ,

Do you have a schedule for when I3C will be implemented on the bus between BIC and BMC?

Thanks,
Yi-Shum

**Comment by Yi-Shum** [comment]
Hi @DelphineChiu,
Do you have information about this?

Thanks,
Yi-Shum

**Comment by DelphineChiu** [comment]
@Yi-Shum 

So far we don't have plan on this.
And Meta team is considering to use MCTP over I3C for BMC-BIC communication and is working on the proposal and plan.

**Comment by Yi-Shum** [comment]
OK, thanks for your reply.
