### ISSUE TITLE
Add OEM command to read/write BIC register

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#179]
Hi @DelphineChiu,

We want to add an OEM command to read and write BIC register for debug.
Do you have any suggestion for this?

Thanks,
Yi-Shum

**Comment by DelphineChiu** [comment]
Hi @Yi-Shum ,

I think make the command data includes the following are enough:

1. Specify read or write
2.
For read: <start address> <length>
For write: <start address> <length <= 4bytes> <data>

Feel free to go with better idea.
Thanks for contributing 

Delphine

**Comment by Yi-Shum** [comment]
Hi @DelphineChiu,

Thanks for your suggestion, we will add this command.

Yi-Shum

**Comment by Yi-Shum** [comment]
Added in #183
