### ISSUE TITLE
I2C master write read question

### ISSUE THREAD

**Issue by MouchenHung-QUANTA** [facebook/OpenBIC#194]
Hi @DelphineChiu

We have a question about master write read command (NF:0x06, CMD:0x52).

In yv3, command's bus-id uses 0-base, but 1-base in yv3.5. Is that reasonable for you?

By the way, 0-base is specified in ipmi spec.

Thanks,
Mouchen

**Comment by SaraLin-wiwynn** [comment]
Hi @MouchenHung-QUANTA ,

We will change both BMC and BIC function of the I2C master write read from 1-base to 0-base, thank you.

Regards,
Sara

**Comment by MouchenHung-QUANTA** [comment]
Fix in cc404e186adff4223973ee9c45d7652122ef7a86
