### ISSUE TITLE
Move sensor monitoring changes from main to main_v2

### ISSUE THREAD

**Issue by BonnieLo** [facebook/OpenBIC#223]
Owner:
Wiwynn

Request from:
#214 , #224 

Description:
The optimization code is based on v2022.07.01. After that, the main branch has been phased in some commits related to sensor monitoring. Those changes will be phased in main_v2.

**Comment by RenChen-wiwynn** [comment]
For this issue, We have fixed this in #229.

**Comment by BonnieLo** [comment]
#229 has been merged.
Close this issue.
