### ISSUE TITLE
The known issue "VR power abnormal assertion when system power on. (VCCD POUT)"

### ISSUE THREAD

**Issue by YoungLi123** [facebook/OpenBIC#272]
Hi @DelphineChiu,

When system DC cycle, the current will drop to 0.

It has a chance to get the negative power value (0xFF 0xFF).

Do we have a plan to filter the negative value for VR power and current like YV3?

Thanks
Young

**Comment by LoraLin1** [comment]
Hi @YoungLi123 
We find this issue from stress test result , and report this issue to the vendor Renesas.
Because VR would report negative current/power value during DC cycle , Renesas recommends that BIC can treat as 0 when receiving current value in -0.2~0.2 A.

Regards,
Lora.

**Comment by YoungLi123** [comment]
#274 #282 fix this issue
