### ISSUE TITLE
Aspeed Zephyr I2C driver overwriting auto-NAK bit?

### ISSUE THREAD

**Issue by peterdelevoryas** [facebook/OpenBIC#364]
https://github.com/AspeedTech-BMC/zephyr/blob/db3dbcc9c52e67a47180890ac938ed380b33f91c/drivers/i2c/i2c_aspeed.c#L1823-L1826

This might be a bug

**Comment by TommyHuang0527** [comment]
Hello!
Thanks for your reminding.
We have fixed it on our side. It will apply on next release.

**Comment by peterdelevoryas** [comment]
Oh great, thanks for fixing that.
