### ISSUE TITLE
OpenBIC MCTP/PLDM implementation

### ISSUE THREAD

**Issue by Eddie043** [facebook/OpenBIC#45]
Hi @rainlinWW,

Because another new project needs to support MCTP and PLDM, do you have a development plan?
If not, Quanta will start to develop it to meet the project schedule.

Thanks,
Eddie

**Comment by rainlinWW** [comment]
Hi @Eddie043,

There is no requirement for supporting MCTP and PLDM in current project, so there is no related schedule.

Thanks,
Rain

**Comment by Eddie043** [comment]
Hi @rainlinWW,

Thanks for your answer.
Quanta will replace the IPMI/IPMB with PLDM/MCTP between BMC and BIC in the new project, so we will start to develop this feature.

Thanks,
Eddie
