### ISSUE TITLE
BIC firmware update is unstable

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#63]
Hi @rainlinWW,

We tested the stability of the BIC firmware update, which was updated 1504 times and failed 208 times.
Have you encountered this problem?

Thanks,
Eason

**Comment by rainlinWW** [comment]
Hi Yi-Shum,

We also run into this issue with SDK 00.01.01.
Will check if issue remain with EVT 01 firmware release tomorrow.

Thanks,
Rain Lin

**Comment by Yi-Shum** [comment]
solved with SDK 00.01.03
