### ISSUE TITLE
BIC warm reset error

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#74]
Hi @rainlinWW,

BIC does not work after warm reboot, but cold reboot works normally.
Have you run into this problem?

Thanks,
Eason

**Comment by rainlinWW** [comment]
Hi Yi-Shum,

We did run into same problem on ast1030-a0 chip.
Both cold and warm reboot works well on our system with ast1030-a1 chip.
Please make sure you are using SDK tag 00.01.03 to build firmware and run on ast1030-a1 CL.

Thanks,
Rain

**Comment by Yi-Shum** [comment]
Hi rainlinWW,

OK, thanks for your reply.

Eason
