### ISSUE TITLE
HSC power threshold

### ISSUE THREAD

**Issue by YoungLi123** [facebook/OpenBIC#76]
Hi @rainlinWW,

The UCT of "HSC Input Pwr" is set to 178W, but it's set to 480W in YV3 project.

Our power team stress the HSC power to 480W, 

For my understanding, it should be 480W, right?

Thanks,
Young

**Comment by rainlinWW** [comment]
Hi Young,

Our EE and power team confirmed that HSC input power should be set higher than 178W.
We will fix the UCT soon after EE provide reasonable threshold for HSC input power.

Thanks,
Rain

**Comment by YoungLi123** [comment]
2021.50.01 solve this issue
