### ISSUE TITLE
HSC init

### ISSUE THREAD

**Issue by YoungLi123** [facebook/OpenBIC#80]
Hi @rainlinWW,

"hsc_init()" doesn't be called by any process.

The "PMON_CONFIG" still use the default setting.

`root@bmc-oob:~# bic-util slot1 0x18 0x52 0x05 0x80 0x02 0xD4
14 07`

Could you help check this?

Thanks,
Young

**Comment by rainlinWW** [comment]
Hi Young,

We will add hsc_init() to device initial functions so HSC config will be set during BIC boot up.

Thanks,
Rain

**Comment by YoungLi123** [comment]
2021.50.01 solve this issue
