### ISSUE TITLE
[EVT] The release schedule for Y35BCL_EVT2

### ISSUE THREAD

**Issue by YoungLi123** [facebook/OpenBIC#83]
Hi @rainlinWW,

From "YV3.5_FW_Table_ODMA_2021_1206.xlsl", the next BIC release will be 12/16.

Is that correct?

The next BIC release which include I2C drive patch is more stable for BMC/BIC communication.

We need this version for the next EVT build.

So we want to know the schedule.

Thanks,
Young

**Comment by rainlinWW** [comment]
Hi Young,

We expect current commits can be merged on 12/17 and we would need Meta side help to release tag for oby35-cl-2021.51.01.

Thanks,
Rain

**Comment by rainlinWW** [comment]
oby35-cl-2021.50.01 (or Y35BCL_EVT2) was released.
