### ISSUE TITLE
[EVT] The release schedule for Y35BCL_EVT3

### ISSUE THREAD

**Issue by YoungLi123** [facebook/OpenBIC#92]
Hi @rainlinWW,

The fix for FRU read #89 has been merged.

This will gate both your and our EVT build.

As I know, next week will release 2021.52.01, right?

Thanks
Young

**Comment by rainlinWW** [comment]
Hi @YoungLi123 

Yes, we will release BIC firmware once every two weeks in EVT.

Thanks,
Rain

**Comment by YoungLi123** [comment]
Hi @rainlinWW

Thanks for your reply

Thanks
Young
