### ISSUE TITLE
Event data of FRB3/CATERR

### ISSUE THREAD

**Issue by Yi-Shum** [facebook/OpenBIC#98]
Hi @rainlinWW,

The value of FRB3, IERR and MCERR is different from Yv3 in sdr.h.
Should we modify it to be the same as Yv3?

event data        | Yv3  | Yv3.5 
--------------|-------|------
IPMI_SDR_SENSOR_SPEC_EVENT_PROCESSOR_IERR    | 0x00 |  0x01 
IPMI_SDR_SENSOR_SPEC_EVENT_PROCESSOR_FRB3    | 0x04 |  0x10
IPMI_SDR_SENSOR_SPEC_EVENT_PROCESSOR_MCERR  | 0x0B |   0x08

Thanks,
Eason

**Comment by rainlinWW** [comment]
Hi @Yi-Shum 

Definition in common/sensor/sdr.h is common definition for all projects.
We don't expect it to be modified for specific project.

Thanks,
Rain

**Comment by Yi-Shum** [comment]
Hi @rainlinWW,

But according to the IPMI specification "42.2 Sensor Type Codes and Data", the definition of event data is same as Yv3.

Thanks,
Yi-Shum

**Comment by Yi-Shum** [comment]
Hi @rainlinWW,

Thanks for your reply.
I was wrong to think the define in sdr.h is used as event data.
The event data is defined in libipmi.h at Yv3, we would copy this file to here and add GPIO interrupt to add FRB3/CATERR event log. 

Thanks,
Yi-Shum
